### ISSUE TITLE
Facebook share button doesn't always show up

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#19]
It looks like a turbolinks issue.  The button will sometimes not show up until you refresh the page.

To reproduce:
1. Create a ride
2. Go to a ride list page, such as my rides
3. Navigate back to the ride, the share button won't show up

**Comment by yashdavisgupta** [comment]
Sticking this here for later reference:
https://developers.facebook.com/docs/reference/javascript/FB.XFBML.parse/
