### ISSUE TITLE
Make UI look nice

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#33]
We need a visual upgrade so the app looks professional and has a distinct, Grinnellian personality.

**Comment by AlexanderOtavka** [comment]
The UI Overhaul is an important step, but there is still significant work to be done.  I'll create relevant issues

**Comment by yashdavisgupta** [comment]
Edit user, forgot password, and change password UI update #55

**Comment by AlexanderOtavka** [comment]
I'm willing to close this, as I think the UI is satisfactory for this milestone.
