### ISSUE TITLE
Improve ride list page

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#39]
Ride lists shouldn't be table layouts in the long term.  Tables don't scale well to mobile, so we need to rework the way we show rides into a list of thumbnails.

This is part of #33.

**Comment by yashdavisgupta** [comment]
I'll take ownership of this. Do we want a table on desktop and thumbnails on mobile or thumbnails on both?

**Comment by AlexanderOtavka** [comment]
Thumbnails for both, but the thumbnails can scale up to show more info/actions on desktop.

**Comment by yashdavisgupta** [comment]
Ok, if we are thinking about thumbnails we should go Masonry. Here is a page explaining it for those interested:
https://www.sitepoint.com/understanding-masonry-layout/
For masonry to make sense, we'll need a pretty comprehensive and intuitive filter/search system.
