### ISSUE TITLE
Add a 'me' page

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#40]
Rather than just the "My Rides" button on the ride list, there should be a dedicated "Me" page with account-related links and a list of current and past rides.

**Comment by yashdavisgupta** [comment]
Are we doing the whole #! with user avatar for comments?

**Comment by AlexanderOtavka** [comment]
Let's make user avatars a different issue. For now, #43 should be enough, with just names. I think we can make this page even without names though, and add them in later.
