### ISSUE TITLE
Side nav unresponsive (maybe do bottom nav instead?)

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#41]
Sometimes when navigating between pages, the sidenav becomes unresponsive.

**Comment by AlexanderOtavka** [comment]
The answer to this might just be abandoning the side nav completely in favor of a bottom nav.

**Comment by yashdavisgupta** [comment]
Fixed. We can still look into a bottom nav in the future.
I think this stackexchange discussion may be helpful:
https://ux.stackexchange.com/questions/112298/which-is-better-side-menu-or-fixed-bottom-menu
As an android user, bottom navs bug the hell out of me (read first answer), but I'm open to a larger conversation. As far as cutting down on taps, I think I have a solution for that too.

**Comment by yashdavisgupta** [comment]
#56
