### ISSUE TITLE
Fix devise pages on small screens

### ISSUE THREAD

**Issue by AlexanderOtavka** [AlexanderOtavka/ride-board#65]
None of the devise pages behave well on phone-sized screens.  This fix should include a refactor to use a shared layout for those pages.

**Comment by yashdavisgupta** [comment]
Cannot replicate on Pixel 2 XL. Can you give step to reproduce or device it isn't working on? One issue I've identified is the button is far too big for the password reset, it should contain less text.

**Comment by AlexanderOtavka** [comment]
I think this was another case of the dev tools responsive layout actually being the source of the bug.  There are still issues on /users/edit and /passwords/new, but the other pages are actually fine.

Let's roll this back into PR #57 and resolve it there.
